#define ETHERNET_RESET_PIN 9    //Pins de reset i chip select (els altres per defecte)
#define ETHERNET_CS_PIN 10

#define N_INPUTS 2
#define PHOTODIODE_PIN_1ST 3
#define PHOTODIODE_PIN_2ND 4
//#define PHOTODIODE_PIN_3RD 6
//#define PHOTODIODE_PIN_4TH 8

#define PHOTODIODE_ID_1ST 0
#define PHOTODIODE_ID_2ND 1
//#define PHOTODIODE_ID_3RD 2
//#define PHOTODIODE_ID_4TH 3

#define PLUG_SENSOR_PIN 0

#define N_LIGHT_RELAYS 4
#define LIGHT_RELAY_PIN_1ST 2
#define LIGHT_RELAY_PIN_2ND 4
#define LIGHT_RELAY_PIN_3RD 6
#define LIGHT_RELAY_PIN_4TH 8
#define ALL_LIGHTS 4

#define LASER_RELAY_PIN 25 
//#define HAZER_RELAY_PIN 26

#define PHOTODIODE_TRESHOLD_DEFAULT_1ST  9
#define PHOTODIODE_TRESHOLD_DEFAULT_2ND  9
//#define PHOTODIODE_TRESHOLD_DEFAULT_3RD  10
//#define PHOTODIODE_TRESHOLD_DEFAULT_4TH  80

//#define HAZER_PERIOD_MILLIS 1000
